"""Engine, session dependency, and the host's own schema.

Demonstrates: the **host side** of the ``migrate(engine)`` contract row — the
part that has to happen *before* any package chain runs.

This host owns two tables (``agent``, ``ticket`` — plus ``ticket_attachment``)
and creates them with ``SQLModel.metadata.create_all``. A real application would
own an Alembic chain here instead; what matters for the contract is only the
*ordering*, and both shapes have the same ordering requirement: the host's
schema first, then each package's ``migrate()``.

Why the order is not arbitrary: ``migrate()`` is adopt-or-create. It looks for
its own tables to decide whether it is adopting a brownfield database. Running
it before the host's own schema exists is fine on a greenfield database and
wrong on an adopting one, so the rule is stated once, here, and the lifespan
follows it.
"""

from __future__ import annotations

from typing import Generator

from sqlalchemy.engine import Engine
from sqlmodel import Session, SQLModel, create_engine

from .config import settings

# ``check_same_thread`` is SQLite's requirement under a threaded server, not an
# Asas one; it appears here so the zero-config SQLite default actually works.
_connect_args = (
    {"check_same_thread": False} if settings.database_url.startswith("sqlite") else {}
)

engine: Engine = create_engine(settings.database_url, connect_args=_connect_args)


def host_tables() -> list:
    """This host's own tables, named explicitly. See ``create_host_schema``."""
    from .models import Agent, Ticket, TicketAttachment

    return [Agent.__table__, Ticket.__table__, TicketAttachment.__table__]


def create_host_schema(bind: Engine) -> None:
    """The host's own tables. Step 1 of the boot sequence in ``main.py``.

    **The trap, and it bites immediately.** ``SQLModel.metadata`` is a single
    process-global registry. Importing an Asas package registers *its* models
    into that same registry, so a bare ``SQLModel.metadata.create_all(bind)``
    silently creates every package's tables too. The package's own ``migrate()``
    then finds them already present and fails — on SQLite,
    ``table clearance_level already exists``.

    Worse, it fails *inconsistently*: the tables exist but no package version
    table records a revision, which is precisely the brownfield shape. So the
    error a host actually sees depends on import order and on whether they got
    as far as calling ``migrate()`` at all.

    The fix is to name your own tables. Never call ``create_all`` without
    ``tables=``, in any host that imports an Asas package.

    A host with its own Alembic chain sidesteps this entirely, because an
    autogenerated chain only contains what its ``env.py`` targets — which is why
    a real application should own a chain here instead. This host uses
    ``create_all`` to stay small enough to read, and pays for that with this
    docstring.
    """
    SQLModel.metadata.create_all(bind, tables=host_tables())


def get_session() -> Generator[Session, None, None]:
    """The FastAPI session dependency.

    Every package router factory takes exactly this callable — ``build_routers``
    and ``build_router`` are handed the host's dependency rather than making
    their own, which is what keeps sessions, transactions and testing overrides
    the host's business.
    """
    with Session(engine) as session:
        yield session
