"""`asas new` — scaffold a FastAPI project pre-wired for a chosen set of
Asas packages.

The output is plain, editable Python — not a runtime abstraction. Every
generated call is real (see templates.py); TODOs mark exactly where the
host must supply its own policy/data. Re-running `asas new` never touches
an existing project directory — it always starts a fresh one."""

from __future__ import annotations

from pathlib import Path

from . import templates
from .git_tags import latest_tags
from .registry import PackageSpec, dependency_string, resolve

_BASE_DEPENDENCIES = (
    'fastapi>=0.110,<1',
    'sqlmodel>=0.0.16',
    'uvicorn[standard]>=0.29',
    'pydantic-settings>=2',
)


def _indent(lines: tuple[str, ...], prefix: str) -> str:
    out = []
    for line in lines:
        for sub in line.split("\n"):
            out.append(f"{prefix}{sub}" if sub else "")
    return "\n".join(out)


def _dedup_preserve_order(items: list[str]) -> list[str]:
    seen: set[str] = set()
    result = []
    for item in items:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result


def _render_main_py(project_name: str, keys: list[str]) -> str:
    imports: list[str] = []
    setup_blocks: list[str] = []
    boot_blocks: list[str] = []

    for key in keys:
        snippet = templates.get(key)
        imports.extend(snippet.imports)
        if snippet.setup:
            setup_blocks.append(
                f"# ── {key} " + "─" * max(1, 60 - len(key)) + "\n" + "\n".join(snippet.setup)
            )
        if snippet.boot:
            boot_blocks.append(f"        # ── {key}\n" + _indent(snippet.boot, "        "))

    extra_imports = "\n".join(_dedup_preserve_order(imports))
    setup_code = "\n\n".join(setup_blocks) if setup_blocks else "# (nothing needs module-level setup)"
    boot_code = (
        "\n\n".join(boot_blocks)
        if boot_blocks
        else "        pass  # (nothing selected needs migrate/seed)"
    )

    content = f'''"""Generated by `asas new` for {project_name} — wired for: {", ".join(keys)}.

This file is real, editable code, not a runtime abstraction — read every
TODO below, fill in your host-specific hooks, then treat it like any other
file in your app. Re-running `asas new` never edits this file; it only
starts a fresh project directory.
"""

from fastapi import FastAPI
from sqlmodel import Session, create_engine
{extra_imports}

from settings import AppSettings

settings = AppSettings()
engine = create_engine(settings.database_url)


def get_session():
    with Session(engine) as session:
        yield session


app = FastAPI(title="{project_name}")

{setup_code}


@app.on_event("startup")
def _boot() -> None:
    with Session(engine) as session:
{boot_code}
'''
    return content.replace("{project_name}", project_name)


def _render_settings_py(keys: list[str]) -> str:
    fields: list[tuple[str, str, str]] = [("database_url", "str", '"sqlite:///./app.db"')]
    seen_names = {"database_url"}
    for key in keys:
        for name, type_, default in templates.get(key).settings_fields:
            if name not in seen_names:
                seen_names.add(name)
                fields.append((name, type_, default))

    field_lines = "\n".join(f"    {name}: {type_} = {default}" for name, type_, default in fields)

    return f'''"""Generated by `asas new`. This is a normal pydantic-settings object —
extend it freely. Reads matching environment variables (case-insensitive)
and a local `.env` file automatically."""

from pydantic_settings import BaseSettings, SettingsConfigDict


class AppSettings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

{field_lines}
'''


def _render_pyproject_toml(project_name: str, specs: list[PackageSpec], versions: dict[str, str]) -> str:
    deps = list(_BASE_DEPENDENCIES) + [
        dependency_string(spec, versions[spec.dist_name]) for spec in specs
    ]
    deps_block = ",\n".join(f'    "{d}"' for d in deps)
    return f'''[project]
name = "{project_name}"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
{deps_block},
]

# What the generated README's `pip install -e '.[dev]'` step installs:
# pytest to run tests/, httpx because fastapi.testclient requires it.
[project.optional-dependencies]
dev = [
    "pytest>=8",
    "httpx>=0.27",
]

# Flat main.py + settings.py, not a package — without this, setuptools'
# auto-discovery sees two top-level modules and refuses to guess which one
# is "the" package, and `pip install -e .` fails outright.
[tool.setuptools]
py-modules = ["main", "settings"]

[tool.pytest.ini_options]
testpaths = ["tests"]
'''


def _render_readme(project_name: str, specs: list[PackageSpec], versions: dict[str, str]) -> str:
    rows = "\n".join(
        f"- **{s.dist_name}** `{versions[s.dist_name]}` ({s.variant}) — {s.summary}"
        for s in specs
    )
    return f'''# {project_name}

Scaffolded by `asas new`. Wired packages, each pinned to its own tag —
packages version independently (see Asas's `RELEASING.md`):

{rows}

## Next steps

1. `pip install -e '.[dev]'` (or `uv sync`)
2. `pytest -q` — the generated smoke test proves the app boots as scaffolded.
3. Open `main.py` and `settings.py` — every `# TODO` marks a host-specific
   hook (policy data, real handlers, real DB URL) the CLI could not know.
4. `uvicorn main:app --reload`

Adding another package later: `asas add <package>`, then wire it into
`main.py` by hand using the same pattern already there — or re-run
`asas new` into a fresh directory and diff.
'''


# One generated test, so the scaffold's core promise — "boots cleanly with
# zero edits" — is checkable by the project's own `pytest` from day one.
_SMOKE_TEST = '''"""Generated by `asas new` — proves the scaffold boots with zero edits."""

from fastapi.testclient import TestClient

import main


def test_app_boots():
    # The context manager runs the startup hook (migrate/seed) too.
    with TestClient(main.app) as client:
        assert client.get("/docs").status_code == 200
'''


def scaffold(
    project_dir: Path,
    project_name: str,
    package_keys: list[str],
    *,
    versions: dict[str, str] | None = None,
) -> list[Path]:
    """Create `project_dir` with a working main.py/settings.py/pyproject.toml
    wired for `package_keys`, each pinned to its own tag (packages version
    independently — see RELEASING.md). `versions` optionally overrides the
    resolved version per dist name (e.g. ``{"asas-lookups": "v0.10.0"}``);
    anything not overridden is resolved to its latest live tag in one remote
    round trip. Refuses if `project_dir` already exists and is non-empty —
    `asas new` only ever starts a fresh project."""
    if project_dir.exists() and (not project_dir.is_dir() or any(project_dir.iterdir())):
        raise FileExistsError(f"{project_dir} already exists and is not empty")

    specs = [resolve(key) for key in package_keys]
    overrides = versions or {}
    to_resolve = [spec.dist_name for spec in specs if spec.dist_name not in overrides]
    resolved_versions = {**overrides, **latest_tags(to_resolve)}

    (project_dir / "tests").mkdir(parents=True, exist_ok=True)

    files = {
        project_dir / "main.py": _render_main_py(project_name, package_keys),
        project_dir / "settings.py": _render_settings_py(package_keys),
        project_dir / "pyproject.toml": _render_pyproject_toml(project_name, specs, resolved_versions),
        project_dir / "README.md": _render_readme(project_name, specs, resolved_versions),
        project_dir / ".env.example": "DATABASE_URL=sqlite:///./app.db\n",
        project_dir / "tests" / "test_smoke.py": _SMOKE_TEST,
    }
    for path, content in files.items():
        path.write_text(content)

    return list(files.keys())
